# Generated by Django 4.1.3 on 2022-12-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srivats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='college',
            new_name='institution',
        ),
    ]
